### ISSUE TITLE
Node-red not working anymore

### ISSUE THREAD

**Issue by Keltere** [estbeetoo/node-red-contrib-marantz-http#7]
Hi, i have a marantz m-cr611 and i've installed everything and setup it but when i deploy the node-red went crazy and now it won't boot.

```
13 Jan 15:13:53 - [info] Starting flows
13 Jan 15:13:53 - [info] [marantz-http-controller:M-CR611] configuring connection to Marantz at 192.168.0.61:80
13 Jan 15:13:54 - [info] Started flows
13 Jan 15:13:54 - [red] Uncaught Exception:
13 Jan 15:13:54 - TypeError: Cannot read property '0' of undefined
    at getValue (/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/marantz-avr/lib/avreciever.js:48:36)
    at convertStatusToModel (/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/marantz-avr/lib/avreciever.js:72:20)
    at /volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/marantz-avr/lib/avreciever.js:84:23
    at Parser.<anonymous> (/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/marantz-avr/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/marantz-avr/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/marantz-avr/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/marantz-avr/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/marantz-avr/node_modules/sax/lib/sax.js:889:7)
```

**Comment by aborovsky** [comment]
Fixed with: https://github.com/estbeetoo/marantz-avr/commit/77783d00df37d03c7c31066a4470a992ce931e1b
